### ISSUE TITLE
Error Install with Flask-JWT-Login

### ISSUE THREAD

**Issue by XFG9** [afi-dev/Termsteel#6]
Hello,

i tried to install but i got:

  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ user .... \AppData\Local\Temp\pip-install-dagqibp8\flask-jwt-login_372ce447414e4e20ac0341d4898d6c5e\setup.py", line 12, in <module>
          long_description=open('README.md').read(),
      FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by kaelianbaudelet** [comment]
Hey [XFG9](https://github.com/XFG9) !

To fix this error just create a file named 'README.md' inside Termsteel Folder or FlaskJWT

**Comment by XFG9** [comment]
ThxVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Afi ***@***.***> Datum: 08.09.22  14:32  (GMT+01:00) An: afi-dev/Termsteel ***@***.***> Cc: XFG9 ***@***.***>, Author ***@***.***> Betreff: Re: [afi-dev/Termsteel] Error Install with Flask-JWT-Login (Issue #6) 
Hey XFG9
To fix this error just create a file named 'README.md' inside Termsteel Folder
